name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --exclude=external/* --exclude=build/* --filter=-legal/copyright,-whitespace/braces,-readability/casting,-build/include_subdir,-build/header_guard --linelength=120 \
    --quiet --recursive .

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

  unittest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Checkout Submodules
      run : |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DTARGET_GROUP=test
    - name: Build Tests
      run: cmake --build ${{github.workspace}}/build
    - name: Unit Tests
      working-directory: ${{github.workspace}}/build
      run: ctest --verbose
