name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

  unittest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DTARGET_GROUP=test
    - name: Build Tests
      run: cmake --build ${{github.workspace}}/build
    - name: Unit Tests
      working-directory: ${{github.workspace}}/build
      run: ctest --verbose
